// <auto-generated />
namespace OSBE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class modified_total_cost_data_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modified_total_cost_data_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201912211119387_modified_total_cost_data_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
